### ISSUE TITLE
It would be good with a couple of hotkeys to turn on/off this feature 

### ISSUE THREAD

**Issue by RikardSwed** [patrickchiang/obsidian-headings-in-explorer#2]
Sometimes I want to see the headings sometimes not. but going all the way into the menu to turn the plugin off takes too long.

**Comment by patrickchiang** [comment]
Good idea. I've added it as a command "Toggle File Explorer Headings". You can customize a shortcut for that.

![image](https://github.com/patrickchiang/obsidian-headings-in-explorer/assets/4903003/bd21be77-120e-41b1-968c-2ede5ecebd9e)

It's been uploaded to release 1.0.3, you should see it when you update your plugin.
Feel free to add other feature requests/bugs as you see them.

**Comment by RikardSwed** [comment]
Great! and thanks! I will surely come back whenever my mind throws a new idea at me.
